/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yip_yipjnidemo_Signature */

#ifndef _Included_com_yip_yipjnidemo_Signature
#define _Included_com_yip_yipjnidemo_Signature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yip_yipjnidemo_Signature
 * Method:    getCLangString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yip_yipjnidemo_Signature_getCLangString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
